package com.xiaopeng.speech.protocol.event.query;

/* loaded from: classes2.dex */
public class QueryCarControlEvent {
    public static final String CONTROL_CAPSULE_MODE = "control.capsule.mode";
    public static final String CONTROL_COMFORTABLE_DRIVING_MODE_SUPPORT = "control.comfortable.driving.mode.support";
    public static final String CONTROL_ELECTRIC_CURTAIN_SUPPORT = "control.electric.curtain.support";
    public static final String CONTROL_GET_WINDOWS_STATE_SUPPORT = "control.get.windows.state.support";
    public static final String CONTROL_LAMP_SIGNAL_SUPPORT = "control.lamp.signal.support";
    public static final String CONTROL_LEG_HEIGHT_GET = "control.leg.height.get";
    public static final String CONTROL_LOW_SPEED_ANALOG_SOUND_SUPPORT = "control.low.speed.analog.sound.support";
    public static final String CONTROL_SCISSOR_DOOR_LEFT_CLOSE_SUPPORT = "control.scissor.door.left.close.support";
    public static final String CONTROL_SCISSOR_DOOR_LEFT_OPEN_SUPPORT = "control.scissor.door.left.open.support";
    public static final String CONTROL_SCISSOR_DOOR_LEFT_RUNNING_SUPPORT = "control.scissor.door.left.running.support";
    public static final String CONTROL_SCISSOR_DOOR_RIGHT_CLOSE_SUPPORT = "control.scissor.door.right.close.support";
    public static final String CONTROL_SCISSOR_DOOR_RIGHT_OPEN_SUPPORT = "control.scissor.door.right.open.support";
    public static final String CONTROL_SCISSOR_DOOR_RIGHT_RUNNING_SUPPORT = "control.scissor.door.right.running.support";
    public static final String CONTROL_SUPPORT_ENERGY_RECYCLE_REASON = "carcontrol.support.energy.recycle.reason";
    public static final String CONTROL_VIP_CHAIR_STATUS = "control.vip.chair.status";
    public static final String CONTROL_XPEDAL_SUPPORT = "control.xpedal.support";
    public static final String GET_CURR_WIPER_LEVEL = "control.wiper.current.level";
    public static final String GET_EXTRA_TRUNK_STATUS = "carcontrol.extra.trunk.status";
    public static final String GET_MIRROR_STATUS = "carcontrol.mirror.status";
    public static final String GET_PAGE_OPEN_STATUS = "gui.page.open.carcontrol";
    public static final String GET_PSN_SUPPORT_SEAT = "carcontrol.get.psn.support.seat";
    public static final String GET_SET_SPEECH_WAKEUP_STATUS = "carcontrol.set.speech.wakeup.status";
    public static final String GET_STATUS_CLOSE_L_CHARGE_PORT = "charge.alternating.port.off.status";
    public static final String GET_STATUS_CLOSE_R_CHARGE_PORT = "charge.direct.port.off.status";
    public static final String GET_STATUS_LIGHT_ATMOSPHERE_BRIGHTNESS = "control.light.atmosphere.brightness.status";
    public static final String GET_STATUS_LIGHT_ATMOSPHERE_COLOR = "control.light.atmosphere.color.status";
    public static final String GET_STATUS_OPEN_L_CHARGE_PORT = "charge.alternating.port.on.status";
    public static final String GET_STATUS_OPEN_R_CHARGE_PORT = "charge.direct.port.on.status";
    public static final String GET_SUPPORT_CLOSE_TRUNK = "carcontrol.get.close.trunk";
    public static final String GET_SUPPORT_OPEN_TRUNK = "carcontrol.get.open.trunk";
    public static final String GET_SUPPORT_SEAT = "carcontrol.get.support.seat";
    public static final String GET_TRUNK_STATUS = "carcontrol.trunk.status";
    public static final String GET_WINDOW_STATUS = "carcontrol.get.window.status";
    public static final String IS_STEERING_MODE_ADJUSTABLE = "control.control.steering.mode.adjustable";
    public static final String IS_SUPPORT_CLOSE_L_CHARGE_PORT = "charge.alternating.port.on.support";
    public static final String IS_SUPPORT_CLOSE_MIRROR = "carcontrol.support.close.mirror";
    public static final String IS_SUPPORT_CLOSE_R_CHARGE_PORT = "charge.direct.port.off.support";
    public static final String IS_SUPPORT_CONTROL_MIRROR = "control.mirror.rear.set.support";
    public static final String IS_SUPPORT_DRIVING_MODE = "carcontrol.support.driving.mode";
    public static final String IS_SUPPORT_ENERGY_RECYCLE = "carcontrol.support.energy.recycle";
    public static final String IS_SUPPORT_LITE_ATMOSPHERE = "control.support.light.atmosphere";
    public static final String IS_SUPPORT_OPEN_L_CHARGE_PORT = "charge.alternating.port.off.support";
    public static final String IS_SUPPORT_OPEN_R_CHARGE_PORT = "charge.direct.port.on.support";
    public static final String IS_SUPPORT_UNLOCK_TRUNK = "control.trunk.unlock.support";
    public static final String IS_TAIRPRESSURE_NORMAL = "control.is.tairpressure.normal";
    public static final String XPU_NGP_STATUS = "xpu.ngp.status";
}
